# Generated by Django 5.2.4 on 2025-08-15 10:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_post_options_news_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_post',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации'),
        ),
    ]
